services:
 db:
   container_name: palomar-db
   image: postgres:16.3-alpine
   volumes:
     - palomar:/var/lib/postgresql/data
   environment:
     POSTGRES_USER: palomar
     POSTGRES_PASSWORD: palomarTest&123
     POSTGRES_DB: palomar
   ports:
     - 5432:5432


volumes:
 palomar: